Repository autobrr/tqm, pull requests merged in 2025-07, with the labels that each got.

#59 fix(notifications): don't escape discord embed titles
  pkg/notification/discord.go
Labels: bug

#60 fix(retag): avoid tag duplicates by using maps
  cmd/helpers.go
  pkg/client/qbittorrent.go
  pkg/client/tagInterface.go
Labels: bug

#63 refactor: modernize codebase
  cmd/clean.go
  cmd/orphan.go
  cmd/orphan_test.go
  cmd/root.go
  pkg/client/deluge.go
  pkg/client/qbittorrent.go
  pkg/config/config.go
  pkg/config/torrent.go
  pkg/config/validator.go
  pkg/expression/regex.go
  pkg/notification/discord.go
  pkg/tracker/btn.go
  pkg/tracker/ops.go
  pkg/tracker/red.go
Labels: refactor

#64 perf(qbit): use SetTags if API version is supported
  cmd/helpers.go
  pkg/client/qbittorrent.go
  pkg/client/tagInterface.go
Labels: enhancement, clients:qbittorrent

#76 feat(expression): default tag mode to 'full' if not specified
  README.md
  pkg/expression/compile.go
  pkg/expression/struct.go
Labels: enhancement, config

#66 refactor(tracker): clean up API requests
  pkg/config/torrent.go
  pkg/httputils/httputils.go
  pkg/tracker/bhd.go
  pkg/tracker/btn.go
  pkg/tracker/hdb.go
  pkg/tracker/ops.go
  pkg/tracker/ptp.go
  pkg/tracker/red.go
  pkg/tracker/unit3d.go
Labels: refactor

#77 feat(retag): make tag creation configurable to prevent empty tags
  README.md
  cmd/retag.go
  pkg/client/qbittorrent.go
Labels: enhancement, clients:qbittorrent
