Repository autobrr/tqm, pull requests merged in 2025-03, with the labels that each got.

#19 fix: path check for Deluge when using FreeSpaceGB
  README.md
  client/deluge.go
  cmd/clean.go
  cmd/relabel.go
  cmd/retag.go
Labels: documentation, enhancement, clients:qbittorrent, go, clients:deluge

#20 fix(clean): update hardlink map before file deletion
  cmd/helpers.go
Labels: bug, go

#21 feat(clean): optionally keep data
  README.md
  cmd/clean.go
  cmd/helpers.go
  config/filter.go
Labels: documentation, enhancement

#23 fix(clean): fix optionally keep data toggle
  README.md
  cmd/helpers.go
  config/filter.go
Labels: bug
