Repository autobrr/tqm, pull requests merged in 2025-05, with the labels that each got.

#39 fix(docs): config example code block
  README.md
Labels: documentation

#40 feat(orphan): ignore paths
  README.md
  cmd/orphan.go
  cmd/orphan_test.go
  pkg/config/config.go
  pkg/config/filter.go
Labels: enhancement, config, go

#42 fix(clean): remove unregistered linked torrents
  cmd/helpers.go
Labels: bug, go

#45 feat(qbit): include trackers with torrents list or fallback to fetch
  go.mod
  go.sum
  pkg/client/qbittorrent.go
Labels: enhancement, clients:qbittorrent

#43 refactor(orphan): use atomic.Uint types for counters
  cmd/orphan.go
Labels: refactor

#46 refactor: pass context to external calls
  cmd/clean.go
  cmd/helpers.go
  cmd/orphan.go
  cmd/pause.go
  cmd/relabel.go
  cmd/retag.go
  go.mod
  go.sum
  pkg/client/deluge.go
  pkg/client/interface.go
  pkg/client/qbittorrent.go
  pkg/client/tagInterface.go
  pkg/config/torrent.go
  pkg/expression/check.go
  pkg/expression/compile.go
  pkg/tracker/bhd.go
  pkg/tracker/btn.go
  pkg/tracker/hdb.go
  pkg/tracker/interface.go
  pkg/tracker/ops.go
  pkg/tracker/ptp.go
  pkg/tracker/red.go
  pkg/tracker/unit3d.go
Labels: enhancement, clients:qbittorrent, refactor, clients:deluge

#48 refactor(cmd): remove unused trace logging
  cmd/clean.go
  cmd/orphan.go
  cmd/pause.go
  cmd/relabel.go
  cmd/retag.go
Labels: refactor
